services:
  - type: web
    name: chatya-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./chatya.db
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 120
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 30
      - key: UPLOAD_DIR
        value: ./uploads
      - key: FRONTEND_URL
        value: "*"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: APP_NAME
        value: ChatYa
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.9
